id = "siri"
name = "Siri Theme"
version = "0.0.12"
schema_version = 1
authors = ["Per Ragnar Edin <perragnar@gmail.com>"]
description = "ğŸ¶ A couple of dark themes based on One Dark and Visual Studio Code dark theme. Also a light theme for bright light coding."
repository = "https://github.com/perragnar/zed-theme-siri"
